m4 solution
Signed-off-by: Michael Yuan <michael@secondstate.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@ on:
         required: true
         default: 'info'
   push:
-    branches: [ main ]
+    branches: [ main, m4 ]
   pull_request:
     branches: [ main ]
 
@@ -50,9 +50,17 @@ jobs:
           echo -e "Execution Fail!"
           exit 1
         fi
-        resp=$(curl http://localhost:8001/find_rate -X POST -d "12345")
+        resp=$(curl http://localhost:8001/find_rate -X POST -d "54921")
         echo "$resp"
-        if [[ $resp == "0.08" ]]; then
+        if [[ $resp == "0.055" ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        resp=$(curl -v http://localhost:8001/find_rate -X POST -d "12345")
+        echo "$resp"
+        if [[ $resp == *"404 Not Found"* ]]; then
           echo -e "Execution Success!"
         else
           echo -e "Execution Fail!"
